### ISSUE TITLE
Is it possible to change the boot order so Windows is the default OS?

### ISSUE THREAD

**Issue by Shadimar** [jlobue10/SteamDeck_rEFInd#11]
Is it possible to change the boot order so Windows is the default OS?  Thanks for this awesome script!

**Comment by jlobue10** [comment]
Thank you for the kind words. Yes, this is actually just a simple edit to the `refind.conf` file. Just change the `default_selection 1` line to be `default_selection 2`, and this should have Windows boot by default with the way I have the `refind.conf` file setup.

**Comment by Shadimar** [comment]
If I have already run the script, there shouldn't be any problems just running it again, right? :)  Thanks for the super-fast response!!

**Comment by jlobue10** [comment]
Good question. I think this part gets lost in the README. There are two ways to edit: you choose. Either after the rEFInd script has already been ran, you can do the `sudo nano /esp/efi/refind/refind.conf` route and edit and save from the command line, or you can open the cloned directory and find the `refind.conf` file there and use a GUI editor like `Kate` or `Emacs`. After editing the cloned directory version, you would just re-run the `./SteamDeck_rEFInd_install.sh` command.

**Comment by Shadimar** [comment]
I was able to do this!  Thank you so much for the explanation!  Happy Holidays!

**Comment by lilpetamoix** [comment]
Hi, I tried the `default_selection 2` but it didn't work.  Upon typing efibootmgr, it looks like windows boot manager is in boot 3.  The bootorder shows windows boot manager (disabled-without asterik), rEFInd, SteamOS.  In order to change the bootorder within rEFInd, do i change to `default_selection 3` instead to the disabled windows boot manager? sorry i'm a little confused.

**Comment by jlobue10** [comment]
@lilpetamoix The `default_selection 2` in this instance is actually due to how I have the manual boot stanzas at the end of the default `refind.conf` file (not boot number from `efibootmgr`). With the default config provided, the order left to right is SteamOS (1) and Windows (2). How did you edit the config file? Did you edit it directly in the installed directory with `sudo nano /esp/efi/refind.refind.conf` or did you edit the config file in the cloned directory? A setting of `default_selection Microsoft` should also work.

**Comment by jlobue10** [comment]
Oh okay, I see what is going on here. I think you edited the wrong config file. Those 2 EFI partitions that Windows sees and mounts are not actually the proper EFI system partition (`/esp`). SteamOS uses those redundant EFI-A and EFI-B partitions for some reason (possibly branch changes but I'm unsure). I would suggest either making the edit in the cloned directory from SteamOS and then re-running the script to install it, or just edit from the command line with `sudo nano /esp/efi/refind.refind.conf` and then press `Ctrl+x` followed by `y` and then `Enter`. Either `default_selection 2` or `default_selection Microsoft` should work, as long as you are editing the correct config file. Hopefully this makes sense.

**Comment by lilpetamoix** [comment]
Yes got it working.  the path was actually `/esp/efi/refind/refind.conf` and not `/esp/efi/refind.refind.conf`.  I couldn't figure out why the window opened but showed nothing until I made that change.  I also didn't realize `Ctrl+x` was to save the file after making the change to `default_selection 2`.

It now works flawlessly.

Thank you for your help and fast turn around!  Much appreciated from a noob Linux environment user.  Thx again!!

**Comment by jlobue10** [comment]
Yes, that was a typo from me. README has correct path. Happy you got it working how you like it. Happy to help. :)
