### ISSUE TITLE
Corrupted screen in Windows

### ISSUE THREAD

**Issue by PhilippeCadieux** [jlobue10/SteamDeck_rEFInd#23]
Hi,

I have followed the installation instructions in the readme and got the bootloader to work just fine so that's great. My issue however is that when I get to Windows, the screen is completely corrupted.

I have found the section of the readme talking about this and how to fix it but that doesn't appear to work for me. I comment all the resolution lines in the conf file, reboot and I get the sideways loader. Then, if I pick Windows I get to windows and everything is looking perfect. I have the right resolution and the right orientation. Then, I uncomment the "resolution 3" line and I'm back to Windows being corrupted. 

My current workaround is that I am leaving all the resolution lines commented so both OSs are working ok but the boot loader is in Portrait mode. Not the end of the world but not ideal. 

Am I missing something obvious somewhere? 

Thanks!

**Comment by PhilippeCadieux** [comment]
Fixed it. Turns out that despite having definitely installed all the drivers after installing Windows, it looks like the AMD Windows drivers were corrupted. I reinstalled them and now everything is working normally. 

Sorry for the false alarm!

**Comment by jlobue10** [comment]
No worries. This issue seems to be a pain point for some people. I found some strangeness with one instance of installing the APU driver where the resolution was 1,280 x 832 afterwards for some odd reason. I corrected that and the boot up resolution with a registry edit, and I was able to avoid this entirely. More details can be found in this older [comment of mine on Reddit](https://www.reddit.com/r/WindowsOnDeck/comments/yro719/comment/ivy4uai/?utm_source=share&utm_medium=web2x&context=3).
