### ISSUE TITLE
Cant install latest Version on newest Beta

### ISSUE THREAD

**Issue by preacha** [jlobue10/SteamDeck_rEFInd#32]
Hi,

i get an error while installation on the newest Beta Version of SteamOS. 

![image](https://user-images.githubusercontent.com/7067861/215340331-6fcec194-40bc-49af-af84-13c823323a73.png)

Link on desktop will be created anyway but seems like something is missing:
![image](https://user-images.githubusercontent.com/7067861/215340406-6a2823a5-33c6-4116-9857-bd116b3e0281.png)

Files from installation folder please see screenshot. Seems like the file "rEFind_Gui" is missing, doesnt it?
![image](https://user-images.githubusercontent.com/7067861/215340434-fad55a6d-0e7e-4f0f-a60f-72cacc13e603.png)
![image](https://user-images.githubusercontent.com/7067861/215340525-0b992dd3-1c59-46a5-8f95-f500920e75f0.png)

**Comment by jlobue10** [comment]
Yes, the link won't work if the compile failed (no binary compiled to shortcut to). Switching branches is one of the times the 'A' and 'B' redundant partitions come into play. Can you try these two manually from the command line, and then re-running the `install-GUI.sh` afterwards? This will help with my debug process.

```
sudo pacman -Syu base-devel
sudo pacman -Syu  glibc hwinfo linux-api-headers qt5-base
```
This is basically force reinstalling the dependencies, since some seem to be missing for compile time. Please let me know how it goes.

**Comment by preacha** [comment]
Did not work as i got also errors here:
![grafik](https://user-images.githubusercontent.com/7067861/215343248-e2909f27-4cbc-403a-a98b-b2dee096c5be.png)
![grafik](https://user-images.githubusercontent.com/7067861/215343295-ad99215f-0b80-42c5-837e-73dcf4930082.png)

**Comment by jlobue10** [comment]
I'm working on reproducing your issue now. Did you make root partition writeable first? Before those 2 commands, you also need to run `sudo steamos-readonly disable`.

**Comment by jlobue10** [comment]
I just cloned and compiled successfully on beta, by the way. I am unable to reproduce your error on my end.

**Comment by preacha** [comment]
The command `sudo steamos-readonly disable ` seems to fix the problem. I don't remember having to use this before (it worked before the recent updates to the GUI version), but I may have had this over enabled at some point and it was reset by an update. Either way, maybe that should be included in the installation instructions then, or did I just overlook it?

Anyway great work with this script. Thank you so much.

**Comment by jlobue10** [comment]
The GUI README instructions genuinely need a lot of work to be brought up to being as thorough as I'd like. I will work on it this week. It's still somewhat of a miracle that I got this GUI to be as high quality as quickly as I did, working nights and weekends over the last few months (on GUI design and callback functions). Once I started working on the C++ stuff, I figured most of the code out in 2 weeks or less. Some parts were definitely trickier than others. I figured since I had tested it thoroughly enough and the GUI is mostly intuitive (I hope), I could release earlier this week and update the README later. I'm guessing in your situation, the swap to beta branch moved which root partition that was booting (A vs. B) and some necessary dependency files were missing. It seems reinstalling those fixed your issue. Please close if you're happy with the solution. I will definitely add this to the README when I get a chance.

**Comment by preacha** [comment]
OK wow, the effort was definitely worth it. With the GUI it is much more comfortable. Really great work.
Thanks for your support and don't overwork yourself.

**Comment by jlobue10** [comment]
For sure. I definitely didn't overwork it, and this was genuinely satisfying intellectually to figure all the way out. Funnily enough, on the Sunday when I had it all mentally figured out in my head, but was still on daddy day care duty, I had to put the baby in the front pocket carrier and do some typing (and he fell asleep... XD). It was just eating away at me to finish. Thanks for the kind words and appreciation, and enjoy the GUI! I think it really makes getting the exact rEFInd configuration that anyone wants incredibly easy, which was my design goal all along.
