### ISSUE TITLE
Windows sd card

### ISSUE THREAD

**Issue by mdesloover** [jlobue10/SteamDeck_rEFInd#33]
Hi, 
Tested for a config with Windows sd card and the config file is well generated. However, partition uuid came with correct identifier but in lowcase format. Switching to uppercase format solves the problem. 
Should be checked un the code!! But Nice work!

**Comment by jlobue10** [comment]
Yes, I'm aware the GUUID comes in lowercase due to how the code is grabbing that information with `hwinfo`. In my limited test cases booting from a Windows SD card (not my normal setup), whether the GUUID was lowercase or not didn't matter. The SD card still booted fine. Are you claiming that with lowercase GUUID, you Windows SD card does not boot properly?

And yes if necessary, I can have the string switched to uppercase, but I'd rather not add the code complexity unless it's actually in my necessity. In my testing, it was not necessary for proper operation.

**Comment by jlobue10** [comment]
The code has been updated for the system call to return all caps to the GUI program for config file generation (using a `tr` function call at the end for formatting). Please update your cloned repository, recompile the GUI and test. If you're happy with the "fix," please close the issue. Thank you.

**Comment by mdesloover** [comment]
Sorry you're right lowercase or'uppercase doesnt matter. Was on a false test case. I edited it manually to even have à mix of lowercase and uppercase and it boots fine

**Comment by jlobue10** [comment]
All good. I "fixed" it anyways, as this may be OCD triggering for some people. Code was just updated. Please try it out.

**Comment by mdesloover** [comment]
I usé thé reinstall-gui.Sh but still generated un lowercase format

**Comment by jlobue10** [comment]
Did you grab the updated `[mainwindow.cpp](https://github.com/jlobue10/SteamDeck_rEFInd/blob/main/GUI/src/mainwindow.cpp)` file? I find the easiest way is to just delete the cloned repo folder and re-clone it. If you're still using the old `mainwindow.cpp` file to compile with, you wouldn't see the change.

**Comment by mdesloover** [comment]
I git pulled it but with the chmod changes it d'identité Overwrite them. William resto de and try that

**Comment by jlobue10** [comment]
Any update? I know it works on my end, and I'd like to close the issue. Thanks.

**Comment by mdesloover** [comment]
Yes, i just had time to retest it. And its now on uppercase format, good
job and thanks
