### ISSUE TITLE
refind didn't work if I launch windows system

### ISSUE THREAD

**Issue by Ye-Tian-Zero** [jlobue10/SteamDeck_rEFInd#34]
It works fine with steamos that each time I restart my steamdeck, **refind** will be launched for me to choose the system.
But once I chose windows, it will not work correctly. Windows will be auto launched without **refind** when I restart the system.
But after I manually boot with **refind**, and launch steamos. Then it workes fine again in future restarts.

**Comment by jlobue10** [comment]
You need to either disable the Windows EFI file using EasyUEFI from Windows, or from a command line in the SteamOS recovery USB session with this following command (replace XXXX with Windows' boot number entry).

`efibootmgr -b XXXX -A`

Alternatively, you can set up the Windows scheduled task using the Powershell script ( `bootsequence-rEFInd-first.ps1` ) from the Windows folder on this repo. You can do either or both of these things, disable the EFI entry and/ or enable the scheduled task. Disabling the EFI entry is probably the easiest. If you don't disable the EFI entry for Windows, then rEFInd cannot assume the highest boot priority (due to current firmware wanting to boot Windows) without some other workaround in place. Hopefully this makes sense. I think this is documented fairly well on the main README page. Please let me know if you have further questions or issues.

**Comment by Ye-Tian-Zero** [comment]
Thanks a lot, it's my fault that I installed rEFInd following a third-party tutorial without reading the official README page. I will check the solution later today, and close the issue now.

**Comment by jlobue10** [comment]
Oh, no worries. This has actually been a pain point for me because the original script from months ago, well before I finished the GUI, was able to take care of disabling the Windows EFI entry during the script run. Something since then has been blocking this command from working in normal SteamOS (hence recovery USB being required). I've been meaning to reach out to the appropriate people at Valve and ask if this is intended behavior (blocking `efibootmgr` ), or if it's a bug,
