### ISSUE TITLE
Uninstall rEFInd?

### ISSUE THREAD

**Issue by thitoro** [jlobue10/SteamDeck_rEFInd#4]
How do I uninstall the rEFInd in Steam Deck?

**Comment by jlobue10** [comment]
I need more information on what you're trying to accomplish and why. Are you going back to SteamOS only (or Windows exclusively)? Due to the nature of possible mistakes on the /esp partition rendering your OSes not bootable, rather than "uninstalling" rEFInd, I would instead recommend either disabling or removing the rEFInd EFI boot entry. Make sure that the OS that you want to be has an active EFI boot entry if you are doing this. To disable the rEFInd boot entry run these two commands from a SteamOS command line.

`efibootmgr`

Take note of the four digit number of the rEFInd boot entry. Replace XXXX with that number in the below command.

`sudo efibootmgr -b XXXX -A`

rEFInd's EFI boot entry would now be disabled, rendering it effectively "uninstalled" and not active. If you want to completely remove the rEFInd EFI boot entry, run this instead.

`sudo efibootmgr -b XXXX -B`

**Comment by thitoro** [comment]
Thanks, jlobue10. I need to do that because I installed my windows on my micro sd. When I installed the refind with these steps, the windows doesn't open with this bootloader because my windows are not in the SSD. Or Can I change that?

**Comment by jlobue10** [comment]
Oh yes, this installation script is mainly intended for people who are dual booting SteamOS and Windows, both from the internal NVMe. Just go with either of the options that I provided. I don't intend to update the script any time soon to support SD card boot entries, since most people I know that dual boot Windows with the SD card, only put the card in when they plan to boot Windows and then perform a button combination to power on the Steam Deck.

**Comment by thitoro** [comment]
Thanks again... I am from Brazil and a few people will like one script to
open the windows from micro SD if you can do this. The micro SD is very
cheap in Brazil that is why. But thank you very much for help me. We are
very happy when we find a person like you.

Have a nice weekend

**Comment by FerLuisxd** [comment]
I would also like to see this updated with an option to set the boot to point to the microSD, I'm on the same boat as @thitoro.

**Comment by jlobue10** [comment]
I'm looking into a triple boot option with SteamOS, Windows and Batocera from the Micro SD card. If and when I provide the alternate config file and alternate script for that, it would be easy enough to infer from the updated config file how to get a different OS to boot from the SD card. It's also already possible with various options turned off in the `refind.conf` file, but I don't plan to re-enable any of those by default at this time. Turning those options off are part of how I achieve the clean minimal look with the bootloader.

**Comment by jlobue10** [comment]
So I just updated the `refind.conf` file to add an SD card option. I will leave detailed uninstall options and procedures to the rEFInd reference page and help people as necessary. Please refer to the "Batocera" manual stanza for an example of how to add a Micro SD card boot option to the rEFInd configuration. It may also be possible for rEFInd to see the Micro SD card EFI boot option automatically if `internal` is re-enabled in the `scanfor` line. Change the `scanfor manual,external` line to be `scanfor manual,external,internal` . I have not personally tested this, but it could possibly work. I think this issue can be closed. There are many references on how to uninstall rEFInd [here](https://www.rodsbooks.com/refind/installing.html).

**Comment by jlobue10** [comment]
Closed. Uninstall references added. SD card example added to latest `refind.conf` file.

**Comment by thitoro** [comment]
But is this will work to Windows in SD cards ?

**Comment by jlobue10** [comment]
It will work with Windows on a Micro SD card, but I have to figure out the proper line for `volume` in the stanza. Reincluding `internal` in `scanfor` may also work, but I have to test that. What version of Windows are you using, 10 or 11? Please open a separate issue for Windows on Micro SD card support, and leave this "Uninstall rEFInd" issue closed. Thank you.

**Comment by thitoro** [comment]
Ok, thanks.
