### ISSUE TITLE
If I use it boot Windows My Speaker is can't work

### ISSUE THREAD

**Issue by LouisChow0306** [jlobue10/SteamDeck_rEFInd#46]
Just Like tittle,if I boot windows by windows bootmanager,speaker can work,but boot by rEFInd,speaker is can't work

**Comment by jlobue10** [comment]
I just confirmed that I do not have this issue on my Steam Deck. I do not think it's rEFInd related, rather it's a Windows setting issue, specifically fast startup. In Windows go to Control Panel->Power Options-> Choose What the power button does, and click on "Change settings that are currently unavailable" and disable "Turn on fast startup (recommended)". This will hopefully fix your issue, if the cause is what I suspect. Please try this and report back. Thanks.

**Comment by LouisChow0306** [comment]
Hello!Today I try to close the fast startup,my Speaker is work,Thank you.
