### ISSUE TITLE
auto restart into windows or steam os?

### ISSUE THREAD

**Issue by xt234** [jlobue10/SteamDeck_rEFInd#53]
so i use the steam deck on a bedroom tv and id like to know if you can set it to start into the other os i have selected.

**Comment by jlobue10** [comment]
Tell me more about your desired setup. It is likely achievable with the proper GUI settings when preforming the 'Create Config' step, or with some manual edit(s) to the `refind.conf` config file.

**Comment by xt234** [comment]
id like it to cycle between oses essentially. so if im on steam os and i restart, it auto restarts into windows and vice versa.

**Comment by jlobue10** [comment]
Yes, this is not supported and there are no plans for me to support this. It seems like a pretty rare use case. It sounds trivial, but implementing it with rEFInd is not a trivial task. With a quick Google search, there do seem to be some GitHub and other sources to accomplish this. They would have to be tailored for SteamOS since SteamOS uses a `/esp` partition whereas other common Linux distros mount that same EFI system partition as `/boot/efi`. I do suggest that you read up on the `default_selection` option in the `refind.conf` config file [here](https://rodsbooks.com/refind/configfile.html). You can set it up to boot different OSes depending on time of. I know this isn't what you wanted or asked for, but that is one of the potential setup options that's fairly easily accomplished.

**Comment by jlobue10** [comment]
Closing this issue as it's not a supported use case and adding support is not planned. Check out [this resource](https://gist.github.com/Darkhogg/82a651f40f835196df3b1bd1362f5b8c) which may have what you are looking for.
