### ISSUE TITLE
Does it work on ChimeraOS ?

### ISSUE THREAD

**Issue by fahad121264** [jlobue10/SteamDeck_rEFInd#58]

**Comment by jlobue10** [comment]
You need to give me more information if you expect my answer to be helpful. What is your desired use case (Dual booting SteamOS and ChimeraOS)? I suppose it could be supported in that case, but I could use some help determining the proper EFI boot file to reference for config file generation.

**Comment by fahad121264** [comment]
ليس لدي steam deck لدي onexplayer سؤالي هو هل يعمل التشغيل المزدوج بين ChimeraOS و windows 11

**Comment by fahad121264** [comment]
don't have a steam deck I have oneexplayer my question is does dual booting work between ChimeraOS and windows 11

**Comment by jlobue10** [comment]
This repo is meant exclusively for Steam Deck since some code base and assumptions are made about the default Steam Deck username. It would probably be relatively easy to clone and/ or fork this repo and make relevant changes to get it to work for Chimera OS and Windows 11, but I don't plan on doing that. The big changes needed would be support for any username ($USER or $HOME), changing `/esp` references to `/boot/efi` and whether or not to add secure boot support or not. Anyways, that is not planned for this repo.

**Comment by jlobue10** [comment]
Not a supported use case.
