### ISSUE TITLE
EXT4 Driver Was Missing

### ISSUE THREAD

**Issue by TumnusB** [jlobue10/SteamDeck_rEFInd#63]
Not sure if it was purposeful or not but the ext4_64.efi driver was not copied into the driver folder, which caused a issue when I was trying to launch Android_x86 via rEFInd, I had to manually copy it over

![Screenshot 2023-05-17 175949](https://github.com/jlobue10/SteamDeck_rEFInd/assets/3604705/69b0812c-08d5-4b61-93d2-71479c458c62)

Update:
Was GUI Install, then used the Pacman option to install rEFInd.

**Comment by jlobue10** [comment]
You are not giving me enough information to be helpful towards diagnosing and fixing a problem. Did you use the GUI to install rEFInd? Did you use the `pacman` or `Sourceforge` method?

**Comment by jlobue10** [comment]
I think this is then more an issue of what the rEFInd installer itself is doing, rather than my helper script and GUI. The install script that the `pacman` option uses (`refind-install` from the rEFInd package) detects and installs the necessary drivers and may leave some out if they are deemed unnecessary. In the case of the Steam Deck, the root filesystems are in `btrfs` not `ext4` so it's likely that the `btrfs` drivers are added and the `ext4` drivers are not. The Sourceforge installation method should not have this same problem, just as an fyi.

It seems you are aware of the issue and fix and nothing is technically wrong with my script to support this rarer use case. I'm not sure what you expect me to 'fix' here.
