### ISSUE TITLE
cannot change new background on New GUI update 

### ISSUE THREAD

**Issue by dtantono** [jlobue10/SteamDeck_rEFInd#88]
before SteamOS 3.5.5 update happens, we can change background theme on GUI. But on 3.5.5, after I clicked create config and install config. it does not worked any more. Is this normal?

![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/39c4c9f6-cca8-49b0-a14e-c94b97a1dea2)

**Comment by jlobue10** [comment]
Icons seem to be okay, but background looks like I may have broken it. I suspect a typo in the code. Give me a few minutes to address and fix and update the release.

**Comment by jlobue10** [comment]
I found the issue. It's not a typo, but it's a real issue. Fixing here shortly.

**Comment by jlobue10** [comment]
Please re-run the installation process and try again. The issue appears to be fixed for me from my testing.

**Comment by dtantono** [comment]
it's getting better. But, when I tried to change to certain png file. I got this error. Is it normal?
![Screenshot_20231120_095327](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/2fbe50b2-3720-40c0-a953-708b384e6f74)

**Comment by jlobue10** [comment]
That error normally just pops up if you typed your password incorrectly...

**Comment by dtantono** [comment]
Hmm, I typed same sudo password  and also clicked "install refind" -> create config ->Install config to ascertain my doubts and it does not worked. But some certain png files works and some are not (I can view the images on image viewer software). Is there any kind of restrictions like filesize restrictions or some kind?

**Comment by jlobue10** [comment]
So the customization issue has likely been fixed in the code. Create config copies the files to the staging location for install config to then copy to the `/esp` partition. Both of those steps seem to be working as intended from my testing.

The only thing I can think of is that the PNG files need to be legitimate PNG files and not just improperly named as such. You can ensure this by opening them in Gimp and exporting them as PNGs (preferably 1,280x800).

**Comment by dtantono** [comment]
Thank you for your advice and it looks better. if new problem arise I will reopen this issue.
